repository: crandmck/doc-site-template
output: web
site_title: Site Title
company_name: 
description: Site description

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000
# the port where the preview is rendered.

exclude:
  - .idea/
  - .gitignore
  - vendor

exclude: [vendor]

plugins:
  - jekyll-redirect-from

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  faqs:
    output: true
    permalink: /faqs/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "faqs"
    values:
      layout: "faq"
      comments: true
      search: true

sidebars:
- home_sidebar

url: https://crandmck.github.io/jekyll-site-template

# baseurl: /

